// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jmsngfbiyqzzwhdgouoo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imptc25nZmJpeXF6endoZGdvdW9vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5OTYzOTksImV4cCI6MjA2ODU3MjM5OX0.itl4F5cqfA78iUYalOy13O_VkrLLOxwd154j20GahpE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});